version: '2.1'
services:
  web:
    image: factorio-api
    expose:
      - "80"
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.factorio_api.rule=Host(`factorio-api.knox.moe`)"
       - "traefik.http.routers.factorio_api.entrypoints=websecure"
       - "traefik.http.routers.factorio_api.tls.certresolver=le"
       - "traefik.docker.network=web_traefik"
    volumes:
       - files_volume:/files

networks:
  default:
    external:
      name: web_traefik

volumes:
  files_volume:

